### ISSUE TITLE
Why FuzzFactory can be made by LLVM 6.0

### ISSUE THREAD

**Issue by Mambaboy** [rohanpadhye/FuzzFactory#6]
Hi guys.
I am interesting in FuzzFactory and want to evaluate its performance by comparing it to naive AFL.
However, AFL cannot be compiled via LLVM 6.0, while FuzzFactory needs LLVM 6.0.
The problem is that there is only one version of LLVM in my computer, how can I deal with it?

Thank you  very much!

**Comment by rohanpadhye** [comment]
Hello.

FuzzFactory is just a fork of AFL, so both should be able to compile on LLVM 6.

If you are getting segfaults when compiling off-the-shelf AFL 2.52b with LLVM 6.0, then you may need to apply the [LLVM patch](https://github.com/rohanpadhye/afl/commit/llvm-fix); I found this on the `afl-users` mailing list but can't remember the original link anymore. This should help you run vanilla AFL on LLVM 6.0.

**Comment by rohanpadhye** [comment]
Oh, actually my commit message in the patch has a link to the original article from the afl-users mailing list: https://groups.google.com/forum/#!msg/afl-users/qGN52REb5lQ/NXIbsFq4BgAJ.

**Comment by Mambaboy** [comment]
Thank you very much
